//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.CreditCards = new HashSet<CreditCard>();
            this.Orders = new HashSet<Order>();
        }
    
        public long userId { get; set; }
        public string loginName { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string postalAddress { get; set; }
        public string country { get; set; }
        public string language { get; set; }
        public bool admin { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_CommentUserId
        /// </summary>
        public virtual ICollection<Comment> Comments { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_CreditCardUserId
        /// </summary>
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_OrderUserId
        /// </summary>
        public virtual ICollection<Order> Orders { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (loginName == null ? 0 : loginName.GetHashCode());
    			hash = hash * multiplier + (password == null ? 0 : password.GetHashCode());
    			hash = hash * multiplier + (firstName == null ? 0 : firstName.GetHashCode());
    			hash = hash * multiplier + (lastName == null ? 0 : lastName.GetHashCode());
    			hash = hash * multiplier + (email == null ? 0 : email.GetHashCode());
    			hash = hash * multiplier + (postalAddress == null ? 0 : postalAddress.GetHashCode());
    			hash = hash * multiplier + (country == null ? 0 : country.GetHashCode());
    			hash = hash * multiplier + (language == null ? 0 : language.GetHashCode());
    			hash = hash * multiplier + admin.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type? 
    
            User target = obj as User;
    
    		return true
               &&  (this.userId == target.userId )       
               &&  (this.loginName == target.loginName )       
               &&  (this.password == target.password )       
               &&  (this.firstName == target.firstName )       
               &&  (this.lastName == target.lastName )       
               &&  (this.email == target.email )       
               &&  (this.postalAddress == target.postalAddress )       
               &&  (this.country == target.country )       
               &&  (this.language == target.language )       
               &&  (this.admin == target.admin )       
               ;
    
        }
    
    
    	public static bool operator ==(User  objA, User  objB)
        {
            // Check if the objets are the same User entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(User  objA, User  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strUser = new StringBuilder();
    
    		strUser.Append("[ ");
           strUser.Append(" userId = " + userId + " | " );       
           strUser.Append(" loginName = " + loginName + " | " );       
           strUser.Append(" password = " + password + " | " );       
           strUser.Append(" firstName = " + firstName + " | " );       
           strUser.Append(" lastName = " + lastName + " | " );       
           strUser.Append(" email = " + email + " | " );       
           strUser.Append(" postalAddress = " + postalAddress + " | " );       
           strUser.Append(" country = " + country + " | " );       
           strUser.Append(" language = " + language + " | " );       
           strUser.Append(" admin = " + admin + " | " );       
            strUser.Append("] ");    
    
    		return strUser.ToString();
        }
    
    
    }
}
